- src/test-runs/test-runs.service.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/7
> Baseline image is removed together with test

- src/builds/builds.service.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/23
> test runs added to build payload

- src/test-runs/test-runs.service.spec.ts
- src/test-runs/test-runs.service.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/46
> diffTollerancePercent default is taken if undefined

- src/events/events.gateway.ts
- src/test-runs/test-runs.service.spec.ts
- src/test-runs/test-runs.service.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/61
> buildUpdated event added

- src/builds/builds.service.spec.ts
- src/builds/builds.service.ts
- src/builds/dto/build-create.dto.ts
- src/prisma/prisma.service.ts
- test/builds.e2e-spec.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/54
> Allow to use project name for build creation

- src/shared/dto/baseline-data.dto.ts
- src/test-runs/dto/create-test-request.dto.ts
- src/test-runs/test-runs.service.ts
- src/test-variations/test-variations.service.spec.ts
- src/test-variations/test-variations.service.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/68
> delete previous test run if exists in scope of one build

- prisma/seed.ts
- src/projects/dto/create-project.dto.ts
- src/projects/dto/project.dto.ts
- src/projects/projects.controller.ts
- src/projects/projects.service.ts
- test/builds.e2e-spec.ts
- test/projects.e2e-spec.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/71
> 71 project edit

- src/app.module.ts
- src/http-prisma-exception.filter.ts
- src/users/users.service.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/73
> 73 register error

- docker-compose.yml
- prisma/Dockerfile
- prisma/entrypoint.sh
- prisma/wait-for-it.sh
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/76
> wait for Postgress added

- README.md
- docker-compose.yml
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/82
> Local sedup doc added

- src/shared/events/events.gateway.ts
- src/test-runs/test-runs.service.spec.ts
- src/test-runs/test-runs.service.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/99
> 99 delete retry

- src/test-runs/dto/create-test-request.dto.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/110
> Update create-test-request.dto.ts. Replace new line characters to support old base64 format

- src/test-runs/dto/create-test-request.dto.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/110
> Update create-test-request.dto.ts. Remove todo

- src/test-runs/dto/testRunResult.dto.ts
- src/test-variations/test-variations.service.spec.ts
- src/test-variations/test-variations.service.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/122
> 122 build status merge fix

- .github/workflows/workflow.yml
- Dockerfile
- prisma/Dockerfile
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/137
> Nodejs downgraded to 12.18.4

- .github/workflows/workflow.yml
- src/builds/dto/build-create.dto.ts
Visual-Regression-Tracker/Visual-Regression-Tracker#142
> ciBuildId validation added

- prisma/entrypoint.sh
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/151
> Add auto approve for migration

- src/builds/builds.controller.ts
- src/builds/dto/build-create.dto.ts
- src/shared/dto/baseline-data.dto.ts
- src/swagger.ts
- src/test-runs/dto/create-test-request.dto.ts
- src/test-variations/test-variations.controller.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/165
> Swagger syntax issues fix

- src/builds/builds.controller.ts
- src/builds/builds.service.spec.ts
- src/builds/builds.service.ts
- src/builds/dto/build.dto.ts
- src/shared/events/events.gateway.ts
- src/shared/shared.module.ts
- src/test-runs/test-runs.controller.ts
- src/test-runs/test-runs.service.spec.ts
- src/test-runs/test-runs.service.ts
- test/builds.e2e-spec.ts
- test/jest-e2e.json
- test/preconditions.ts
- test/test-runs.e2e-spec.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/212
> 212 socker debounce

- src/http-exception.filter.ts
Addresses Issue https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/203
> Issue #203 : implemented user friendly error messages.

- src/shared/events/events.gateway.ts
closes https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/221
> TestRun create event could go later than delete event #221

- src/test-runs/dto/create-test-request.dto.ts
Closes https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/268
> Multipart endpoint could not parse ignoreAreas #268

- package-lock.json
- package.json
- src/compare/compare.module.ts
- src/compare/compare.service.spec.ts
- src/compare/compare.service.ts
- src/compare/libs/image-comparator.interface.ts
- src/compare/libs/looks-same/looks-same.service.spec.ts
- src/compare/libs/looks-same/looks-same.service.ts
- src/compare/libs/odiff/odiff.service.spec.ts
- src/compare/libs/odiff/odiff.service.ts
- src/compare/libs/odiff/odiff.types.ts
- src/compare/libs/pixelmatch/pixelmatch.service.ts
- src/compare/libs/pixelmatch/pixelmatch.types.ts
- src/compare/utils/index.ts
- src/shared/static/static.service.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/277
> feat: Odiff added

- src/shared/dto/custom-tags.dto.ts
- src/test-runs/dto/update-ignore-area.dto.ts
- src/test-runs/dto/update-test.dto.ts
- src/test-runs/test-runs.controller.ts
- src/test-runs/test-runs.service.spec.ts
- src/test-runs/test-runs.service.ts
- src/test-variations/dto/test-variation-update.dto.ts
- src/test-variations/test-variations.controller.ts
- src/test-variations/test-variations.service.spec.ts
- src/test-variations/test-variations.service.ts
- test/test-runs.e2e-spec.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/214
> Move bulk operations on server side

- src/shared/dto/baseline-data.dto.ts
- src/shared/static/static.service.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/262
> Can upload non PNG images

- src/shared/tasks/tasks.service.ts
closes https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/290
> TestVariation clean up process does clean up project main branch

- package-lock.json
- src/test-variations/test-variations.service.ts
closes https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/326
> fix: Exception when using manual merge (Variations screen)

- prisma/package-lock.json
- prisma/package.json
- prisma/seed.ts
This change allow easier use of docker images for test/demonstration purposes
> seed: use fixed APIKEY for default user

- prisma/package-lock.json
- prisma/package.json
- prisma/seed.ts
@nicerloop changed this to internal branch to pass tests
accept organisation invitation so you could work on internal branches
> seed: use fixed APIKEY for default user (#174)

- Dockerfile
- prisma/Dockerfile
Replacement for #203, while fixing #184
> Upgrade Docker images to use LTS version of Node.js #184

- package.json
Replaces #202 to get Codacy token available...
> Use Apache 2 license as the parent project

- .eslintrc.js
- package-lock.json
- package.json
- src/shared/api-file.decorator.ts
- src/test-runs/dto/create-test-request-multipart.dto.ts
- src/test-runs/dto/update-ignore-area.dto.ts
- src/test-runs/test-runs.controller.ts
- src/test-variations/test-variations.controller.ts
This has few errors now revealed and help is needed to fix them...
> Add NestJS plugin for ESLint to start catching issues before upgrade

- src/main.ts
related to Visual-Regression-Tracker/Visual-Regression-Tracker#417
> Fix download images

- src/http-exception.filter.ts
- src/test-runs/dto/update-ignore-area.dto.ts
- test/builds.e2e-spec.ts
- test/preconditions.ts
- test/projects.e2e-spec.ts
- test/test-runs.e2e-spec.ts
- test/test-variations.e2e-spec.ts
- test/users.e2e-spec.ts
closes https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/419
> Fix: cannot add/update ignore areas

- src/builds/builds.service.spec.ts
- src/builds/builds.service.ts
- test/builds.e2e-spec.ts
closes https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/426
> fix(426): Concurrency issue with multiple requests to create build

- package-lock.json
- package.json
- src/static/hdd/hdd.service.ts
Closes https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/449
> fix(#449): filename collisions
