src/shared/static/static.service.ts
src/test-runs/diffResult.ts
src/test-runs/test-runs.controller.ts
src/test-runs/test-runs.service.spec.ts
src/test-runs/test-runs.service.ts

https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/32

32 recalculate

---

src/test-runs/test-runs.service.spec.ts
src/test-runs/test-runs.service.ts

https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/66

Emit build change event when ignore area recalculated

---

src/projects/projects.service.ts
src/test-variations/test-variations.controller.ts
src/test-variations/test-variations.service.spec.ts
src/test-variations/test-variations.service.ts

https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/58

58 variation delete

---

src/test-runs/dto/create-test-request.dto.ts
src/test-runs/test-runs.service.spec.ts
src/test-runs/test-runs.service.ts
src/test-variations/test-variations.service.spec.ts
src/test-variations/test-variations.service.ts

https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/132

132 ignore via api

---

src/builds/builds.controller.ts
src/builds/builds.service.spec.ts
src/builds/builds.service.ts
src/builds/dto/build-modify.dto.ts
src/shared/events/events.gateway.ts
src/test-variations/test-variations.service.spec.ts
src/test-variations/test-variations.service.ts

Addresses https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/197 
Made generic method to modify a build. This method can be used both for stopping or modifying any other feature (like CI build id) of the build. Corresponding frontend changes will also be raised as a pull request.

Issue#197 : Add possibility to update build with ci build id.

---

src/test-runs/test-runs.controller.ts
src/test-runs/test-runs.service.spec.ts
src/test-runs/test-runs.service.ts

https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/213

Switch to client instead of server side pagination

---

src/test-variations/test-variations.service.spec.ts
src/test-variations/test-variations.service.ts

https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/204

TestVariation. Do not remove test run in case deleted #204

---

src/test-runs/test-runs.service.spec.ts
src/test-runs/test-runs.service.ts

closes:  https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/248

Do not compare image if the same buffer

---

src/http-exception.filter.ts

Fixes part of the issue: https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/296

Add clearer error message for unauthorized user

---

src/builds/builds.controller.ts
src/builds/dto/build-create.dto.ts
test/builds.e2e-spec.ts

This will enable SDK and clients not to send branch information. That way, it will use the default branch if not provided.

If branch not sent, take default branch

---

src/test-runs/dto/create-test-request.dto.ts
src/test-runs/test-runs.service.spec.ts
src/test-runs/test-runs.service.ts
test/test-runs.e2e-spec.ts

To support adding comments through SDK, we have to update the test run service to accept optional comment first. 
Details of the request  can be found here: [#312](https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/312)
Tested with postman locally and updated tests, all passing.

feat(312): add optional comment property for test runs

---

package-lock.json
package.json
src/app.module.ts
src/health/health.controller.spec.ts
src/health/health.controller.ts

This PR adds an health check endpoint using [terminus](https://docs.nestjs.com/recipes/terminus) that basically just checks the database connection by running a `SELECT 1` query. 
The goal is to then use it as a readiness probe in a kubernetes deployment.
Related with this issue: https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/362

Add health check endpoint

---

src/shared/tasks/tasks.service.ts

this fixes Visual-Regression-Tracker/Visual-Regression-Tracker#382

let cleanOldTestVariations respect project boundaries

---

src/builds/builds.service.spec.ts
src/compare/libs/pixelmatch/pixelmatch.service.spec.ts
src/test-runs/test-runs.service.spec.ts

After seeing a deprecation warning, followed to https://github.com/jestjs/jest/pull/12089, changed the place where `mocked` method comes from.
... but should `jest-mock` be added specifically to `devDependencies`?

Use mocked from jest-mock instead of ts-jest, since it was moved

---

.github/workflows/workflow.yml
Dockerfile
README.md
docker-compose.yml
jest.config.ts
package-lock.json
package.json
prisma/Dockerfile
test_acceptance/acceptance.spec.ts
test_acceptance/jest.config.ts

Replacing #208 to have cleaner history.
---
Well this keeps failing, most likely `postinstall` of prisma is not triggered or something, but I will look again once #206 is done.

Update GitHub Actions tool versions and keep them consistent

---

README.md
package-lock.json
package.json
prisma/package-lock.json
prisma/package.json

Once every often I have come across the issue where the Prisma client dependency has not been found, even after it was specifically generated.
Looking at
* https://github.com/prisma/prisma/issues/7234
* https://github.com/prisma/prisma/issues/17162
* https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/generating-prisma-client
...got the idea to define where the generated client should go.
Environment variables loaded from .env
Environment variables loaded from prisma/.env
Prisma schema loaded from prisma/schema.prisma
✔ Generated Prisma Client (5.1.1 | library) to ./prisma/node_modules/@prisma/client in 218ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
```
import { PrismaClient } from '@prisma/client'
const …
```

Update Prisma to v5.1.1 and define Node.js 18 LTS as the minimum

---

.github/workflows/workflow.yml
Dockerfile
README.md
docker-compose.yml
prisma/Dockerfile
prisma/schema.prisma

This change fixes that using `odiff` as a diffing backend raises an exception due to ABI incompatibility with `musl-libc` in `alpine` images. 
Using `odiff` with `alpine` based images is a known issue with the upstream dependency (see https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/368#issuecomment-2104074846).
Since this upstream issue is open for quite a while (nearly 4 years), it is easier to address it downstream and use a `debian` based nodejs image instead of the `alpine` one. 
closes https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/368
Changing the migrations base image isn't required, but IMHO adding an additional 20MB to the whole stack isn't a big deal considering the reduced maintenance burden and that 20MB are about 5 …

🩹 Use debian base image to allow using odiff as diffing backend

---

.github/workflows/workflow.yml
Dockerfile
README.md
docker-compose.yml
prisma/Dockerfile
prisma/schema.prisma

* 👌 Use debian base image to allow usage of odiff
Odiff isn't ABI compatible with musl-libc (alpine) and thus causes crashes when called. Where as debian uses gnu-libc which is compatible with the odiff binaries.
* 🧹 Remove deprecated docker compose file version
Ref.: https://github.com/compose-spec/compose-spec/blob/main/spec.md#version-and-name-top-level-elements
* 🤔 Also use debian base image for migrations? (consistency)
Using the same base image for migration and the API might reduce debugging afford for bugs related to prisma alpine/debian differences (i.e. binaryTargets)
* 🩹🚇 Use docker compose v2 CLI call in workflow
This fixes the error: "docker-compose: command not found"

🩹 Use debian base image to allow using odiff as diffing backend (#297)

---

Dockerfile
prisma/Dockerfile
prisma/schema.prisma

api-1        | PrismaClientInitializationError: Prisma Client could not locate the Query Engine for runtime "linux-arm64-openssl-3.0.x".
api-1        |
api-1        | This happened because Prisma Client was generated for "linux-arm64-openssl-1.1.x", but the actual deployment required "linux-arm64-openssl-3.0.x".
api-1        | Add "linux-arm64-openssl-3.0.x" to `binaryTargets` in the "schema.prisma" file and run `prisma generate` after saving it:
api-1        |
api-1        | generator client {
api-1        |   provider      = "prisma-client-js"
api-1        |   binaryTargets = ["native", "debian-openssl-3.0.x", "linux-arm64-openssl-3.0.x"]
api-1        | }

fix PrismaClientInitializationError

---

.github/workflows/workflow.yml
src/static/aws/s3.service.ts
src/static/hdd/hdd.service.ts
src/static/utils.ts

closes https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/462

fix: S3. Change name generation from Date.now to UUID
